FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt

RUN apt-get update && \
    apt-get install -y sqlite3 && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
