version: '3.8'

services:
  banco:
    build:
      context: ./banco
      dockerfile: Dockerfile
    volumes:
      - ./instance:/app/instance
    ports:
      - "5000:5000"
  seletor:
    build:
      context: ./seletor
      dockerfile: Dockerfile
    volumes:
      - ./instance:/app/instance
    ports:
      - "5001:5001"

  validador1:
    build:
      context: ./validador
      dockerfile: Dockerfile
    volumes:
      - ./instance:/app/instance
    ports:
      - "5002:5002"

  validador2:
    build:
      context: ./validador
      dockerfile: Dockerfile
    volumes:
      - ./instance:/app/instance
    ports:
      - "5003:5003"

  validador3:
    build:
      context: ./validador
      dockerfile: Dockerfile
    volumes:
      - ./instance:/app/instance
    ports:
      - "5004:5004"

  validador4:
    build:
      context: ./validador
      dockerfile: Dockerfile
    volumes:
      - ./instance:/app/instance
    ports:
      - "5005:5005"
