version: '3.8'
services:
  banco:
    build: ./banco
    ports:
      - "5000:5000"
    command: python ./main.py

  seletor:
    build: ./seletor
    ports:
      - "5001:5001"
    command: python seletor/app.py
    depends_on:
      - banco
  validador1:
    build: .
    ports:
      - "5002:5002"
    command: python validador/validador.py --port=5002
  validador2:
    build: .
    ports:
      - "5003:5003"
    command: python validador/validador.py --port=5003
  validador3:
    build: .
    ports:
      - "5004:5004"
    command: python validador/validador.py --port=5004
  validador4:
    build: .
    ports:
      - "5005:5005"
    command: python validador/validador.py --port=5005

  